Update some name
linuxcnc-probe-screen/probe-screen-ng pull request #41
Opened 2020-12-25 16:49 UTC by alkabal

update var probeheight as setterheight
update toolchange-number as toolchange-prep-number
add toolchange-number 
change logic for actual toolnumber self.stat.tool_in_spindle no more used

2020-12-27 15:08 UTC, kiall requested changes

2020-12-27 15:08 UTC, kiall commented on psng/psng.hal
> +net tool-diameter          probe.toolchange-diameter    <=   halui.tool.diameter
The `probe.toolchange-diameter` pin doesn't exist.

2020-12-27 15:29 UTC, alkabal commented
Oh yes sorry

it’s a potential future pr for diameter measurements (full rewrites)

2020-12-27 16:23 UTC, alkabal commented
change done, thank you for pointing that

2020-12-28 13:50 UTC, kiall approved these changes

2020-12-28 13:50 UTC, merged

2020-12-28 15:25 UTC, alkabal commented
i speak about ask false to input hal pin ?

2020-12-28 15:27 UTC, kiall commented
> i speak about ask false to input hal pin ?

I've no idea what you mean?